use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Category {
    StoriesOfLegend,
    RegularEventStages,
    CollabStages,
    EmpireOfCats,
    IntoTheFuture,
    CatsOfTheCosmos,
    EventStages,
    ContinuationStages,
    DojoHallOfInitiates,
    TowersAndCitadels,
    DojoRankingEvents,
    ChallengeBattle,
    UncannyLegends,
    CataminStages,
    LegendQuest,
    ZombieOutbreaks,
    GauntletStages,
    EnigmaStages,
    CollabGauntletStages,
    AkuRealms,
    BehemothCulling,
    Labyrinth,
    ZeroLegends,
    OtherworldColosseum,
    CatclawChampionships,
    LegacyPrincessPunt,
    Unknown(String),
}

impl Category {
    pub fn from_prefix(prefix: &str) -> Self {
        match prefix.to_uppercase().as_str() {
            "N"        => Self::StoriesOfLegend,
            "RS" | "S" => Self::RegularEventStages,
            "C"        => Self::CollabStages,
            "EC"       => Self::EmpireOfCats,
            "W"        => Self::IntoTheFuture,
            "SPACE"    => Self::CatsOfTheCosmos,
            "RE"       => Self::EventStages,
            "EX"       => Self::ContinuationStages,
            "RT" | "T" => Self::DojoHallOfInitiates,
            "RV" | "V" => Self::TowersAndCitadels,
            "RR" | "R" => Self::DojoRankingEvents,
            "M"        => Self::ChallengeBattle,
            "NA"       => Self::UncannyLegends,
            "B"        => Self::CataminStages,
            "D"        => Self::LegendQuest,
            "Z"        => Self::ZombieOutbreaks,
            "A"        => Self::GauntletStages,
            "H"        => Self::EnigmaStages,
            "CA"       => Self::CollabGauntletStages,
            "DM" | "U" => Self::AkuRealms,
            "Q"        => Self::BehemothCulling,
            "L"        => Self::Labyrinth,
            "ND"       => Self::ZeroLegends,
            "SR"       => Self::OtherworldColosseum,
            "G"        => Self::CatclawChampionships,
            "PT"       => Self::LegacyPrincessPunt,
            _          => Self::Unknown(prefix.to_string()),
        }
    }

    pub fn display_name(&self) -> &str {
        match self {
            Self::StoriesOfLegend      => "Stories of Legend",
            Self::RegularEventStages   => "Regular Event Stages",
            Self::CollabStages         => "Collab Stages",
            Self::EmpireOfCats         => "Empire of Cats",
            Self::IntoTheFuture        => "Into the Future",
            Self::CatsOfTheCosmos      => "Cats of the Cosmos",
            Self::EventStages          => "Event Stages",
            Self::ContinuationStages   => "Continuation Stages",
            Self::DojoHallOfInitiates  => "Dojo Hall of Initiates",
            Self::TowersAndCitadels    => "Towers & Citadels",
            Self::DojoRankingEvents    => "Dojo Ranking Events",
            Self::ChallengeBattle      => "Challenge Battle",
            Self::UncannyLegends       => "Uncanny Legends",
            Self::CataminStages        => "Catamin Stages",
            Self::LegendQuest          => "Legend Quest",
            Self::ZombieOutbreaks      => "Zombie Outbreaks",
            Self::GauntletStages       => "Gauntlet Stages",
            Self::EnigmaStages         => "Enigma Stages",
            Self::CollabGauntletStages => "Collab Gauntlet Stages",
            Self::AkuRealms            => "Aku Realms",
            Self::BehemothCulling      => "Behemoth Culling",
            Self::Labyrinth            => "Labyrinth",
            Self::ZeroLegends          => "Zero Legends",
            Self::OtherworldColosseum  => "Otherworld Colosseum",
            Self::CatclawChampionships => "Catclaw Championships",
            Self::LegacyPrincessPunt   => "Legacy Princess Punt",
            Self::Unknown(prefix)      => prefix.as_str(),
        }
    }

    pub fn base_id(&self) -> Option<u32> {
        match self {
            Self::StoriesOfLegend      => Some(0),
            Self::RegularEventStages   => Some(1),
            Self::CollabStages         => Some(2),
            Self::EmpireOfCats         => None,
            Self::IntoTheFuture        => None,
            Self::CatsOfTheCosmos      => None,
            Self::EventStages          => Some(4),
            Self::ContinuationStages   => Some(4),
            Self::DojoHallOfInitiates  => Some(6),
            Self::TowersAndCitadels    => Some(7),
            Self::DojoRankingEvents    => Some(11),
            Self::ChallengeBattle      => Some(12),
            Self::UncannyLegends       => Some(13),
            Self::CataminStages        => Some(14),
            Self::LegendQuest          => Some(16),
            Self::ZombieOutbreaks      => None,
            Self::GauntletStages       => Some(24),
            Self::EnigmaStages         => Some(25),
            Self::CollabGauntletStages => Some(27),
            Self::AkuRealms            => Some(30),
            Self::BehemothCulling      => Some(31),
            Self::Labyrinth            => Some(33),
            Self::ZeroLegends          => Some(34),
            Self::OtherworldColosseum  => Some(36),
            Self::CatclawChampionships => Some(37),
            Self::LegacyPrincessPunt   => None,
            Self::Unknown(_)           => None,
        }
    }

    pub fn global_map_id(&self, local_map_id: u32) -> Option<u32> {
        self.base_id().map(|base| (base * 1000) + local_map_id)
    }

    pub fn sort_order(&self) -> u32 {
        match self {
            Self::StoriesOfLegend      => 0,
            Self::RegularEventStages   => 1,
            Self::CollabStages         => 2,
            Self::EmpireOfCats         => 3,
            Self::IntoTheFuture        => 3,
            Self::CatsOfTheCosmos      => 3,
            Self::EventStages          => 4,
            Self::ContinuationStages   => 5,
            Self::DojoHallOfInitiates  => 6,
            Self::TowersAndCitadels    => 7,
            Self::DojoRankingEvents    => 11,
            Self::ChallengeBattle      => 12,
            Self::UncannyLegends       => 13,
            Self::CataminStages        => 14,
            Self::LegendQuest          => 16,
            Self::ZombieOutbreaks      => 20,
            Self::GauntletStages       => 24,
            Self::EnigmaStages         => 25,
            Self::CollabGauntletStages => 27,
            Self::AkuRealms            => 30,
            Self::BehemothCulling      => 31,
            Self::Labyrinth            => 33,
            Self::ZeroLegends          => 34,
            Self::OtherworldColosseum  => 36,
            Self::CatclawChampionships => 37,
            Self::LegacyPrincessPunt   => 98,
            Self::Unknown(_)           => 99,
        }
    }
}